name: Auto Rebuild on Base Image Update

on:
  push:
    branches:
        - IP-675_notify-slack
  schedule:
    - cron: '0 2 * * *' # Run day at 2am
  workflow_dispatch:

jobs:
  check-base-image:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest digest for Debian bookworm-slim
        id: digest
        run: |
          DIGEST=$(docker buildx imagetools inspect debian:bookworm-slim --format '{{json .Manifest.Digest}}')
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Check if digest changed
        id: check
        run: |
          CURRENT=$(grep -o 'sha256:[a-f0-9]\+' images/apache/apache-dl-proxy/Dockerfile)
          if [[ "$CURRENT" != "${{ steps.digest.outputs.digest }}" ]]; then
            echo "Base image changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No change"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Dockerfile if needed
        if: steps.check.outputs.changed == 'true'
        run: |
          sed -i "s|sha256:[a-f0-9]\+|${{ steps.digest.outputs.digest }}|" images/apache/apache-dl-proxy/Dockerfile
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Update base image digest"
          git push

  build:
    runs-on: ubuntu-latest
    needs: check-base-image
    
    if: needs.check-base-image.outputs.changed == 'true'

    steps:
        
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ENV_DOCKER_USER }}
          password: ${{ secrets.ENV_DOCKER_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./images/apache/apache-dl-proxy
          file: ./images/apache/apache-dl-proxy/Dockerfile
          push: true
          tags: kingstonduo/apache-dl-proxy:latest
        
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
            status: custom
            fields: job
            custom_payload: |
              {
                attachments: [{
                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
                }]
              }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.ENV_SLACK_PASSCODE }}
        if: always()

